version: "3.9"

services:
  humid-subscriber:
    build:
      context: ./Subscriber/Humid
    container_name: humid-subscriber
    working_dir: /Humid
    network_mode: host
    restart: on-failure

  temp-subscriber:
    build:
      context: ./Subscriber/Temp
    container_name: temp-subscriber
    working_dir: /Temp
    network_mode: host
    restart: on-failure

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot

volumes:
  grafana-storage:

networks:
  iot:
    driver: bridge
